### ISSUE TITLE
Diep.io Protocol

### ISSUE THREAD

**Issue by firebolt55439** [devenlil/Bliep.io-Client#3]
Hey,
I see you're trying to make your own diep.io client. In order to do that, you'll need to know the protocol that diep.io uses to communicate (e.g. what are the packets, etc.).

We have a project dedicated to just that here: https://github.com/firebolt55439/Diep.io-Protocol. Feel free to check it out! We'd love it if you could help us out as well :)

**Comment by devenlil** [comment]
Thanks for letting me know! I'll check it out and see if I can help out with anything.
